- .eslintrc.yml
- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- test/test-client.js
- test/test-e2e.js
- test/test-message.js
- test/test-server.js
- test/util.js
Built via github automated workflow
> tools: add actions CI

- .github/workflows/nodejs.yml
> tools: maybe fix cache?

- .github/workflows/publish.yml
This uses github actions to auto publish to npm when there is a tag 🎉
> tools: auto publish to npm on tag

- README.md
- package.json
* client + server
* update package.json description
> doc: improve description

- .github/workflows/publish.yml
> tools: add auto-generated release notes to release

- README.md
> docs: fix listing event example

- .github/workflows/publish.yml
> tools: more tweaks to auto publish action

- .github/workflows/bump-version.yml
This will allow me to publish new releases from the
GitHub UI!
> tools: create bump version workflow

- .github/workflows/nodejs.yml
Getting duplicate runs on tags being pushed right now
> tools: only run workflow on push to main branch and PR

- .github/workflows/create-release.yml
> tools: update release script to use POST API

- .github/workflows/create-release.yml
Time for a new version of node
> tools: update create-release to nodejs 16

- .github/workflows/bump-version.yml
Probably doesn't matter much but just figured I'd make a quick PR to update the comment referencing the job name.
> Fix comment referencing the job name.

- .github/workflows/bump-version.yml
> tools: use choices for workflow inputs

- .github/workflows/codeql-analysis.yml
> tools: add codeql analysis

- .github/workflows/nodejs.yml
> tools: add node 17 to CI

- package-lock.json
> deps: fix audit warnings

- .github/workflows/bump-version.yml
- .github/workflows/create-release.yml
Remove the need for a deploy key and make the workflows copy pastable!
> tools: no more deploy key

- .github/workflows/bump-version.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create-release.yml
- .github/workflows/nodejs.yml
> Update actions version and remove deploy key

- .github/workflows/nodejs.yml
update latest versions of actions and include node.js 19
> chore: update actions

- .github/workflows/create-release.yml
Update deps + publish with provenance
> tools: update release automation

- package-lock.json
> deps: update

- .github/workflows/create-release.yml
The new version has provenance support built in.
https://github.com/npm/cli/pull/6163
> Update to use latest npm CLI release

- lib/Server.mjs
- test/test-server.mjs
Fixes: https://github.com/MylesBorins/node-osc/issues/98
> server: ensure host argument is used

- lib/Server.mjs
- lib/internal/decode.mjs
- package.json
- rollup.config.mjs
- test/test-decode.mjs
Fixes: https://github.com/MylesBorins/node-osc/issues/104
> Handle edge case with decoding 

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- rollup.config.mjs
This pull request includes changes related to linting and configuration files. The most important changes include modifying the `lint` script in `package.json` to include the `rollup.config.mjs` file for linting, removing a `console.log` statement in `rollup.config.mjs`, and adding a missing semicolon in `rollup.config.mjs`.
Configuration and linting changes:
* <a href="diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L27-R30">`package.json`</a>: Modified the `lint` script to include the `rollup.config.mjs` file for linting.
* <a href="diffhunk://#diff-47407fecafdf5f5cd55403c3de457833ddf9b6fab45253c04e1dc4c7cb4495b1L67">`rollup.config.mjs`</a>: Removed a `console.log` statement and added a missing semicolon. <a …
> chore: small updates

- package-lock.json
- test/util.mjs
Mostly non eventful. Needed to change util function though.
> chore: update deps

- .devcontainer/devcontainer.json
> tools: add devcontainer.json
